designproject/designapp/urls.py
from django.urls import path
from . import views

app_name = 'designapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.ApplicationListView.as_view(), name='profile'),
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('admin_profile/', views.AdminProfileView.as_view(), name='admin-profile'),
]

urlpatterns += [
    path('create', views.create_application, name='application-create'),
    path('application/<int:application_id>/delete/', views.delete_application, name='application-delete'),
]

urlpatterns += [
    path('admin_categories/', views.CategoryListView.as_view(), name='admin-category-list'),
    path('admin_categories_add/', views.CategoryCreateView.as_view(), name='admin-category-add'),
    path('admin_categories_delete/<int:category_id>/', views.CategoryDeleteView.as_view(), name='admin-category-delete'),
    path('admin_change_status/<int:application_id>/', views.ChangeStatusView.as_view(), name='change-status'),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

designproject/designproject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.urls import include
from django.urls import path
urlpatterns += [
    path('designapp/', include('designapp.urls', namespace='designapp')),
]


from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/designapp/', permanent=True)),
]

urlpatterns += [
path('accounts/', include('django.contrib.auth.urls')),
]

from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

designproject/designapp/models.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import AbstractUser
import re
class CustomUser(AbstractUser):
    first_name = models.CharField(max_length=150, blank=False, verbose_name='Имя')
    last_name = models.CharField(max_length=150, blank=False, verbose_name='Фамилия')
    username = models.CharField(max_length=150, unique=True, blank=False, verbose_name='Логин')
    email = models.EmailField(unique=True, blank=False, verbose_name='Электронная почта')
    middle_name = models.CharField(max_length=150, blank=False, verbose_name='Отчество')
    password1 = models.CharField(max_length=128, blank=False, null=True, verbose_name='Пароль')
    password2 = models.CharField(max_length=128, blank=False, null=True, verbose_name='Повтор пароля')
    consent = models.BooleanField(default=False, verbose_name='Я соглашаюсь на обработку моих персональных данных')

    def clean(self):
        super().clean()
        if not re.match(r'^[А-Яа-яЁёs-]*$', self.last_name):
            raise ValidationError('Фамилия должна содержать только кириллические буквы, пробелы и дефисы.')
        if not re.match(r'^[А-Яа-яЁёs-]*$', self.first_name):
            raise ValidationError('Имя должно содержать только кириллические буквы, пробелы и дефисы.')
        if self.middle_name and not re.match(r'^[А-Яа-яЁёs-]*$', self.middle_name):
            raise ValidationError('Отчество должно содержать только кириллические буквы, пробелы и дефисы.')
        if not self.consent:
            raise ValidationError('Необходимо согласие на обработку персональных данных.')


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


# Заявки:
import os
from django.urls import reverse
class Application(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='applications')
    timestamp = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255, blank=False)
    description = models.TextField(blank=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    status = models.CharField(max_length=50, default='Новая')  # Например, 'Принято в работу', 'Выполнено', 'Новая'
    photo = models.ImageField(upload_to='photos/', null=True, blank=False)
    comment = models.TextField(null=True, blank=False)
    design_image = models.ImageField(upload_to='designs/', null=True, blank=False)

    @property
    def photo_name(self):
        return os.path.basename(self.photo.name)

    def clean(self):
        super().clean()
        if self.photo:
            if self.photo.size > 2 * 1024 * 1024:  # 2 MB
                raise ValidationError("Размер фото не должен превышать 2 МБ.")
            if not self.photo.name.lower().endswith(('.png', '.jpg', '.jpeg', '.bmp')):
                raise ValidationError("Недопустимый формат файла. Используйте jpg, jpeg, png, bmp.")

    def get_absolute_url(self):
        return reverse('application-detail', args=[str(self.id)])

    def __str__(self):
        return self.title

designproject/designapp/forms.py
from django import forms
from .models import CustomUser
class CustomUserCreationForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('last_name', 'first_name', 'middle_name', 'username', 'email', 'password1', 'password2', 'consent')


from django.contrib.auth.forms import AuthenticationForm
class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password']


from .models import Application
class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['title', 'description', 'category', 'photo']

designproject/designapp/views.py
from django.shortcuts import render

# Create your views here.
from .models import Application


def index(request):
    # Получаем последние выполненные заявки из базы данных
    applications = Application.objects.filter(status='Выполнено').order_by('-timestamp')[:4]  # Получаем последние 4 выполненные заявки
    accepted_count = Application.objects.filter(status='Принято в работу').count()  # Подсчет заявок в статусе "Принято в работу"

    context = {
        'applications': applications,
        'accepted_count': accepted_count,
    }
    return render(request, 'designapp/index.html', context)


from django.views import generic
class ApplicationListView(generic.ListView):
    model = Application
    template_name = 'designapp/application_list.html'
    context_object_name = 'applications'

    def get_queryset(self):
        queryset = Application.objects.filter(user=self.request.user)
        status = self.request.GET.get('status')  # Получаем статус из GET-параметров
        if status:
            queryset = queryset.filter(status=status)  # Фильтруем по статусу
        return queryset


from .forms import ApplicationForm
def create_application(request):
    if request.method == 'POST':
        form = ApplicationForm(request.POST, request.FILES)
        if form.is_valid():
            application = form.save(commit=False)  # Не сохраняем сразу
            application.user = request.user  # Устанавливаем текущего пользователя
            application.save()
            return redirect('designapp:profile')
    else:
        form = ApplicationForm()

    return render(request, 'designapp/application_create.html', {'form': form})


from django.shortcuts import get_object_or_404
def delete_application(request, application_id):
    application = get_object_or_404(Application, id=application_id)
    if request.method == 'POST':
        application.delete()
        return redirect('designapp:profile')
    return render(request, 'designapp/confirm_delete.html', {'application': application})


from django.shortcuts import redirect
from .forms import CustomUserCreationForm
def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])  # Хранение пароля в зашифрованном виде
            user.save()
            login(request, user)
            return redirect('designapp:index')
    else:
        form = CustomUserCreationForm()

    return render(request, 'registration/register.html', {'form': form})


from .forms import CustomAuthenticationForm
def login_user(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('designapp:index')
            else:
                form.add_error(None, 'Неверный логин или пароль.')
    else:
        form = CustomAuthenticationForm()

    return render(request, 'registration/login.html', {'form': form})


from django.contrib.auth import login, authenticate, logout
def logout_user(request):
    logout(request)
    return render(request,'registration/logged_out.html')


from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin
class AdminProfileView(LoginRequiredMixin, UserPassesTestMixin, generic.TemplateView):
    template_name = 'designapp/admin_profile.html'

    def test_func(self):
        return self.request.user.is_superuser  # Проверка, является ли пользователь администратором

    def get_context_data(self, **kwargs):
        # Вызов метода родительского класса, чтобы получить контекст
        context = super().get_context_data(**kwargs)

        # Получение всех заявок со статусом "Новая"
        context['applications'] = Application.objects.filter(status='Новая')

        return context


from django.contrib import messages
from .models import Category
from django.views import View
class CategoryListView(LoginRequiredMixin, UserPassesTestMixin, View):
    template_name = 'designapp/manage_categories.html'

    def get(self, request):
        categories = Category.objects.all()
        return render(request, self.template_name, {'categories': categories})

    def test_func(self):
        return self.request.user.is_superuser


class CategoryCreateView(LoginRequiredMixin, UserPassesTestMixin, View):
    def post(self, request):
        name = request.POST.get('name')
        if name:
            Category.objects.create(name=name)
            messages.success(request, 'Категория добавлена!')
        else:
            messages.error(request, 'Введите название категории.')
        return redirect('designapp:admin-category-list')

    def test_func(self):
        return self.request.user.is_superuser


class CategoryDeleteView(LoginRequiredMixin, UserPassesTestMixin, View):
    def post(self, request, category_id):
        try:
            category = Category.objects.get(id=category_id)
            category.delete()  # Удаление категории
            messages.success(request, 'Категория удалена!')
        except Category.DoesNotExist:
            messages.error(request, 'Категория не найдена.')
        return redirect('designapp:admin-category-list')

    def test_func(self):
        return self.request.user.is_superuser


class ChangeStatusView(LoginRequiredMixin, UserPassesTestMixin, View):
    def get(self, request, application_id):
        application = get_object_or_404(Application, id=application_id)
        return render(request, 'designapp/change_status.html', {'application': application})

    def post(self, request, application_id):
        application = get_object_or_404(Application, id=application_id)

        status = request.POST.get('status')
        comment = request.POST.get('comment')
        design_image = request.FILES.get('design_image')

        if status == 'Принято в работу':
            if comment:
                application.status = status
                application.comment = comment
                application.save()
                messages.success(request, 'Статус успешно изменён на "Принято в работу".')
            else:
                messages.error(request, 'Необходимо заполнить комментарий для "Принято в работу".')

        elif status == 'Выполнено':
            if design_image:
                application.status = status
                application.design_image = design_image
                application.save()
                messages.success(request, 'Статус успешно изменён на "Выполнено".')
            else:
                messages.error(request, 'Необходимо загрузить изображение для "Выполнено".')

        return render(request, 'designapp/change_status.html', {
            'application': application,
            'messages': messages.get_messages(request)
        })

    def test_func(self):
        return self.request.user.is_superuser

designproject/designapp/templates/designapp/Admin_profile.html
{% extends "base.html" %}
{% block title %}<title>Личный кабинет администратора</title>{% endblock %}
{% block content %}
    <div class="admin-profile">
        <h2>Личный кабинет администратора</h2>
        <a href="{% url 'designapp:admin-category-list' %}" class="btn">Управление категориями заявок</a>

        {% for application in applications %}
            <div class="application-item">
                <h4>{{ application.title }}</h4>
                <a href="{% url 'designapp:change-status' application.id %}">Смена статуса заявки</a>
            </div>
        {% empty %}
            <p>Нет заявок со статусом "Новая".</p>
        {% endfor %}

    </div>
{% endblock %}

designproject/designapp/templates/designapp/application_create.html
{% extends "base.html" %}
{% block title %}<title>Создать заявку</title>{% endblock %}
{% block content %}
    <h2>Создать заявку</h2>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать</button>
    </form>

    {% if form.errors %}
        <ul>
            {% for field in form %}
                {%for error in field.errors%}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

designproject/designapp/templates/designapp/application_list.html
{% extends "base.html" %}
{% block title %}<title>Личный кабинет</title>{% endblock %}
{% block content %}
<div class="container">
    <div class="sidebar">
        <h2>Меню</h2>
        <ul>
            <li><a href="{% url 'designapp:application-create' %}">Создание заявки</a></li>
        </ul>
    </div>

    <main>
        <h2>Мои заявки:</h2>
        <form method="get" action="">
            <select name="status" id="status" onchange="this.form.submit()">
                <option value="Новая" {% if request.GET.status == 'Новая' %}selected{% endif %}>Новые</option>
                <option value="Принято в работу" {% if request.GET.status == 'Принято в работу' %}selected{% endif %}>Принятые в работу</option>
                <option value="Выполнено" {% if request.GET.status == 'Выполнено' %}selected{% endif %}>Выполненные</option>
            </select>
        </form>

        <table>
            <thead>
                <tr>
                    <th>Название</th>
                    <th>Категория</th>
                    <th>Дата создания</th>
                    <th>Статус</th>
                    <th>Изображение</th>
                    <th>Удалить заявку</th>
                </tr>
            </thead>
            <tbody>
                {% for application in applications %}
                <tr>
                    <td>{{ application.title }}</td>
                    <td>{{ application.category }}</td>
                    <td>{{ application.timestamp }}</td>
                    <td>{{ application.status }}</td>
                    <td>{{ application.photo_name }}</td>
                        <td><a href="{% url 'designapp:application-delete' application.id %}">Удалить</a></td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="6">Заявок нет</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </main>
</div>
{% endblock %}

designproject/designapp/templates/designapp/change_status.html
{% extends "base.html" %}
{% block title %}<title>Смена статуса заявки</title>{% endblock %}
{% block content %}
<a href="{% url 'designapp:admin-profile' %}">Назад</a>
<div class="admin-change-status">
    <h2>Смена статуса заявки: {{ application.title }}</h2>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="status">Выберите новый статус:</label>
        <select name="status" id="status" required onchange="this.form.submit()">
            <option value="">-- Выберите статус --</option>
            <option value="Выполнено" {% if application.status == "Выполнено" or request.POST.status == "Выполнено" %}selected{% endif %}>Выполнено (с изображением)</option>
            <option value="Принято в работу" {% if application.status == "Принято в работу" or request.POST.status == "Принято в работу" %}selected{% endif %}>Принято в работу (с комментарием)</option>
        </select><br><br>

        <div id="design-image-field" style="display: {% if request.POST.status == 'Выполнено' %}block{% else %}none{% endif %};">
            <label for="design_image">Прикрепите изображение созданного дизайна:</label>
            <input type="file" name="design_image" accept="image/*" {% if application.status != "Выполнено" %}required{% endif %}><br><br>
        </div>

        <div id="comment-field" style="display: {% if request.POST.status == 'Принято в работу' %}block{% else %}none{% endif %};">
            <label for="comment">Введите комментарий:</label>
            <textarea name="comment" required>{% if request.POST.comment %}{{ request.POST.comment }}{% endif %}</textarea><br><br>
        </div>

        <button type="submit">Изменить статус</button>
    </form>
</div>
{% endblock %}

designproject/designapp/templates/designapp/confirm_delete.html
{% extends "base.html" %}
{% block title %}<title>Удаление заявки</title>{% endblock %}
{% block content %}
<h2>Подтвердите удаление заявки</h2>
<p>Вы уверены, что хотите удалить заявку "{{ application.title }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Удалить</button>
    <a href="{% url 'designapp:profile' %}">Отмена</a>
</form>
{% endblock %}

designproject/designapp/templates/designapp/index.html
{% extends "base.html" %}
{% block title %}<title>Главная страница</title>{% endblock %}
{% block content %}
<h2>Последние выполненные заявки</h2>
<div class="applications">
    <!-- Пример заявок -->
    {% for application in applications %}
    <div class="application">
        <img src="{{ application.photo.url }}" alt="{{ application.title }}">
        <p><strong>Временная метка:</strong> {{ application.timestamp }}</p>
        <p><strong>Название:</strong> {{ application.title }}</p>
        <p><strong>Категория:</strong> {{ application.category }}</p>
    </div>
    {% endfor %}
</div>

<div class="counter">
    <h3>Количество заявок в статусе «Принято в работу»: <span id="accepted-count">{{ accepted_count }}</span></h3>
            </div>
{% endblock %}

designproject/designapp/templates/designapp/manage_categories.html
{% extends 'base.html' %}
{% block title %}<title>Управление категориями заявок</title>{% endblock %}
{% block content %}
<a href="{% url 'designapp:admin-profile' %}">Назад</a>
<h2>Управление категориями заявок</h2>
{% if messages %}
    {% for message in messages %}
        <div class="alert">{{ message }}</div>
    {% endfor %}
{% endif %}
<form method="post" action="{% url 'designapp:admin-category-add' %}">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Название категории" required>
    <button type="submit">Добавить категорию</button>
</form>

<h3>Список категорий:</h3>
<ul>
    {% for category in categories %}
        <li>
            {{ category.name }}
            <form method="post" action="{% url 'designapp:admin-category-delete' category.id %}">
                {% csrf_token %}
                <button type="submit">Удалить</button>
            </form>
        </li>
    {% empty %}
        <li>Категорий нет.</li>
    {% endfor %}
</ul>
{% endblock %}